name: NanoZoo Diaper Bag
favicon: null
layout_spectrum: 0.7896374517586082
typography_spectrum: 0.8602976307738572
title: Help Us Kickstarter
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1b1a1f'
    - '#929292'
    - '#4f4f4f'
    - '#727272'
  brandStrength: 0.3125
  lightness: 0.8652479376178235
  saturation: 0.5138830724172294
  rhythmicContrast: 0.19213386462070048
purpose: []
